### ISSUE TITLE
TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by thychamp** [applitools/Eyes.Sdk.JavaScript#69]
I am experiencing an issue when I upgraded from 0.0.83 to 3.6.3.  That is I get the following error.  

```
(node:56795) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'width' of null
    at .../node_modules/eyes.selenium/src/capture/EyesWebDriverScreenshot.js:131:53
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
It is caused by this promise being called

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/6f8206a5f03902d549ef48a6d6936fa9ce4c5ac8/packages/eyes.selenium/src/EyesWebDriver.js#L272-L274

before this promise

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/6f8206a5f03902d549ef48a6d6936fa9ce4c5ac8/packages/eyes.selenium/src/EyesWebDriver.js#L261-L264

Which results in the `that._defaultContentViewportSize` being resolved as `null`.

If you change this around a bit like this, it resolves the issue, becauses the promises are called in the correct order.

```js
promise.then(function () {
                return EyesSeleniumUtils.getViewportSizeOrDisplaySize(that._logger, that._driver, that.getPromiseFactory());
            }).then(function (viewportSize) {
                that._defaultContentViewportSize = viewportSize;
                that._logger.verbose("Done! Viewport size: ", that._defaultContentViewportSize);
            }).then(function () {
                resolve(that._defaultContentViewportSize);
            });
```

However with that change, it leaves this by itself.

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/6f8206a5f03902d549ef48a6d6936fa9ce4c5ac8/packages/eyes.selenium/src/EyesWebDriver.js#L266-L270

I am not sure what that is used for.

**Comment by thychamp** [comment]
I was able to resolve this issue by upgrading to 

```
"@applitools/eyes-selenium": "~4.7.0",
"selenium-webdriver": "~4.0.0-alpha.1",
```
